version: '3'
services:
  redis:
    image: 'redis:4-alpine'
    ports:
      - '6379:6379'
    restart: always
    networks:
      - app-net
  email:
    build: ./email
    environment:
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=$EMAIL_PASSWORD
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - EMAIL_TEST_RECIPIENT=${EMAIL_TEST_RECIPIENT}
    volumes:
      - ./email:/email
    restart: always
    networks:
      - app-net
      - default
    depends_on:
      - redis
  frontend:
    build: ./frontend
    ports:
      - '5007:5007'
    volumes:
      - ./frontend:/frontend
    environment:
      VIRTUAL_HOST: earthquakes.costa365.site
      PORT: 5007
    depends_on:
      - redis
    restart: always
    networks:
      - app-net
      - default
  monitor:
    build: ./monitor
    volumes:
      - ./monitor:/monitor
    depends_on:
      - redis
      - email
    restart: always
    networks:
      - app-net
      - default

networks:
  default:
    external: true
    name: nginx-proxy
  app-net:
    internal: true
